Algoritmo "consumo"

Var

          distanciaPercorrida: inteiro
          combustivelGasto, consumo: real
          


Inicio

          escreva ("Distância percorrida: ")
          leia (distanciaPercorrida)
          escreva ("Combustível gasto: ")
          leia (combustivelGasto)

          consumo <- distanciaPercorrida/combustivelGasto
          
          escreva ("Consumo médio: ", consumo:8:3)

Fimalgoritmo